### ISSUE TITLE
Not interested button not working

### ISSUE THREAD

**Issue by abel-otegbola** [testprojcts/side_hustle_react_capstone_proj1#7]
###The onClick effect in the div with class single-tour__body should be removed and put in the paragraph tag containing the tour.info.

###add the onClick effect to the p tag having the truncPara.info

### in the tour.jsx file add a new state -
  const [showModal, setShowModal] = useState(false);

###finally delete the p tag between the h4(having tour.name) and h4(having tour.price)

**Comment by testprojcts** [comment]
I have the updated the codes.... kindly pull and give it a test run
